language: python
python: 
  - "3.6"
cache: pip

language: r
cache: packages

dist: xenial

sudo: required

addons:
  apt:
    packages:
      - fftw3
  homebrew:
    packages:
      - cmake
      - python3
      - gcc

before_install:
  - pip install numpy scipy pandas scikit-learn numba cffi matplotlib future graphtools tasklogger psutil
  - pip install opentsne
  - pip install umap-learn
  - pip install phate
  - pip install git+https://github.com/jacoblevine/phenograph.git
