language: r

addons:
  apt:
    packages:
      - python3
      - fftw3
  homebrew:
    packages:
      - cmake
      - python3
      - gcc

before_install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install numpy scipy pandas scikit-learn numba cffi matplotlib future graphtools tasklogger psutil
  - pip install opentsne
  - pip install umap-learn
  - pip install phate
  - pip install git+https://github.com/jacoblevine/phenograph.git
