language: r
r:
  - release
cache: packages

dist: xenial

sudo: required

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - fftw3
      - python3.6
      - python3.6-dev
      - libgit2-dev
      - libhdf5-dev
      - libtool
      - libmagick++-dev
  homebrew:
    packages:
      - cmake
      - python3
      - gcc

env:
  global:
    - PYTHON=python3.6

before_install:
  - $PYTHON --version
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H $PYTHON
  - sudo $PYTHON -m pip install --upgrade pip
  - pip install --user numpy scipy pandas scikit-learn numba cffi matplotlib future graphtools tasklogger psutil
  - pip install --user opentsne
  - pip install --user umap-learn
  - pip install --user phate
  - pip install --user git+https://github.com/jacoblevine/phenograph.git
  
r_packages:
  - reticulate
  - parallel
  - glue
  - magrittr
  
bioc_packages:
  - SingleCellExperiment
  - GenomeInfoDbData
  - S4Vectors
  - SummarizedExperiment

Remotes: satijalab/Seurat@release/3.0
