language: r

dist: xenial

sudo: required

addons:
  apt:
    packages:
      - fftw3
  homebrew:
    packages:
      - cmake
      - python3
      - gcc

python: 
  - 3.6.5

before_install:
  - pip install numpy scipy pandas scikit-learn numba cffi matplotlib future graphtools tasklogger psutil
  - pip install opentsne
  - pip install umap-learn
  - pip install phate
  - pip install git+https://github.com/jacoblevine/phenograph.git
